version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Composer"
      include: "scope"
    labels:
      - "composer"
      - "dependencies"
    versioning-strategy: auto
    open-pull-requests-limit: 2    
